### ISSUE TITLE
Wrong Fixture configuration file is read

### ISSUE THREAD

**Issue by KES777** [jjn1056/DBIx-Class-Migration#84] opened 2017-02-05 15:17 UTC
```
$ make dbdeploy 
$(which dbic-migration) --schema_class XXX::Schema --database PostgreSQL -Ilib -V 14 install
Since this database is not versioned, we will assume version 19
Reading configurations from /home/kes/xxx/share/fixtures/19/conf
$ make dbstatus 
$(which dbic-migration) --schema_class XXX::Schema --database PostgreSQL -Ilib status
Schema is 19
Deployed database is 14
```

My current schema version in code is 19. I want manually to test code and deploy schema version 14.
While I do this wrong version is read for fixtures

**Comment by mohawk2** [comment] 2019-02-25 21:58
If you don't give me a set of steps from the start that I can reproduce a problem, I can't fix it. I'm not even asking you to make an automated test. Closing until that changes.

**Comment by KES777** [comment] 2019-02-26 10:43
Here is all what is required: `-V 14`

Just notice that deployed version is 14, but fixtres from 19 version is applied

**Comment by mohawk2** [comment] 2019-02-26 16:35
I don't think you understand me. I need all the steps to reproduce this from the start. If I can't get the problem to happen on my computer, I can't fix it. Simply saying what you need to do on your computer, with your files already in place, is useless.

**Comment by KES777** [comment] 2019-02-27 09:08
1. Take any schema you have
2. Check what is latest version. for example schema version is 50
3. Deploy any version before 50. For example 40
4. Fixtures are read from 40 instead of 50

**Closed** 2019-03-05 16:23 UTC

**Comment by KES777** [comment] 2019-03-05 17:21
thank you

**Comment by mohawk2** [comment] 2019-03-05 18:09
Now released as 0.064

**Comment by KES777** [comment] 2019-05-13 14:31
seems not all is fixed. My `DBIx::Class::Migration` is 0.073

```
# make dbup
$(which dbic-migration) --schema_class HyperMouse::Schema --database PostgreSQL -Ilib upgrade
Reading configurations from /opt/monkeyman/share/fixtures/130/conf
# make dbstatus
$(which dbic-migration) --schema_class HyperMouse::Schema --database PostgreSQL -Ilib status
Schema is 131
Deployed database is 131
```

Here I just upgrade database. Do not know, if that is OK to read old fixtures, when DB is of new version and, probably, do not have fields which were at old `130` version.

**Comment by mohawk2** [comment] 2019-05-14 06:48
Steps to reproduce?

**Comment by KES777** [comment] 2019-05-14 09:56
`dbic-migration --schema_class HyperMouse::Schema --database PostgreSQL -Ilib upgrade`

**Comment by mohawk2** [comment] 2019-05-15 15:14
Since I don't have `HyperMouse::Schema`, that's not a meaningful "step to reproduce", is it.

**Comment by KES777** [comment] 2019-05-15 15:33
Yes, you are right, but it has not matter which schema. Just prepare migration then run [`upgrade`](https://metacpan.org/pod/distribution/DBIx-Class-Migration/lib/DBIx/Class/Migration/Script/Help/upgrade.pod) command
